steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '{{cookiecutter.python_version}}'
      architecture: 'x64'
    displayName: 'Use Python Version {{cookiecutter.python_version}}'

  - script: "python -m pip install --upgrade pip && pip install pipenv"
    displayName: 'Install tools'

  - script: "pipenv install --ignore-pipfile --dev"
    displayName: "Install Dependencies"

  - script: "pipenv run pytest tests --doctest-modules
    --junitxml=build/junit/test-results.xml
    --cov-report=xml:build/coverage.xml
    --cov-report=html:build/htmlcov/"
    displayName: 'Run PyTest'

  - script: "pipenv run python vsts/fix_style.py"
    displayName: 'Fix Test report CSS Style'

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: 'build/**/test-*.xml'
      testRunTitle: 'Test results for build'
    displayName: 'Publish Test Results'

  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: 'cobertura'
      summaryFileLocation: 'build/**/coverage.xml'
      reportDirectory: 'build/**/htmlcov'
      additionalCodeCoverageFiles: 'build/**/htmlcov/**/*.*'
      failIfCoverageEmpty: true
    displayName: 'Publish Code Coverage Results'
